config/routes.rb
Rails.application.routes.draw do
  
  root 'contacts#home' 

  resources :contacts
  
  #get "/print", to: "contacts#print"
  get 'print', to: 'contacts#print'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
require 'prawn'

class Contact < ApplicationRecord
  
  def self.printer
    @contacts = Contact.all
    @pdf = generate_pdf(@contacts)
  end

  def self.generate_pdf(contacts)
    Prawn::Document.generate('Contatos.pdf') do
      formatted_text [ { :text=>"Lista de Contatos", :styles => [:bold], :size => 20 } ]
      move_down 10
      #@contact = Contact.all
      contacts.each do |contact|
        formatted_text [ { :text=>contact.name, :styles => [:bold], :size => 10 } ]
        move_down 2
        formatted_text [ { :text=>"Telefone: #{contact.phone}", :size => 10 } ]
        move_down 2
        formatted_text [ { :text=>"Email: #{contact.email}", :size => 10 } ]
        move_down 6
      end
    end
  end

  private
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
#require 'prawn'

class ContactsController < ApplicationController
  helper_method :printer

  def index
    @contacts = Contact.all
  end

  def print
    HardWorker.perform_async
    redirect_to root_path
  end

  def showpdf(pdf)
    send_data(pdf, :filename => "Contacts.pdf", :type => "application/pdf") 
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact
    else
      render :new
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with model: contact do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone %><br>
    <%= form.text_field :phone %><br>
  </div>

    <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.erb
<h1>Edit Contact</h1>

<%= render "form", contact: @contact %>

app/views/contacts/home.html.erb
<h1>Contacts</h1>

<%= link_to "New Contact", new_contact_path %><br>

<br>

<%= link_to "All Contacts", contacts_path %><br>

<br>

<%= link_to "Print All Contacts", print_path %><br>

<p>Find me in app/views/contacts/index.html.erb</p>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<ul>
  <% @contacts.each do |contact| %>
    <li>
        <%= link_to contact.name, contact %><br>
        <%= contact.phone %><br>
        <%= contact.email %><br>
    </li>
    <br>
  <% end %>
</ul>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render "form", contact: @contact %>

app/views/contacts/show.erb
<h1> <%= @contact.name %> </h1>

<h3> <%= @contact.phone %> </h3>

<h3> <%= @contact.email %> </h3>

<ul>
  <li><%= link_to "Edit", edit_contact_path(@contact) %></li>
  <li><%= link_to "Destroy", contact_path(@contact),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>
  

<p><br>Find me in app/views/contacts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>